name: Snyk Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (required for Snyk CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Step 4: Authenticate Snyk CLI
      - name: Authenticate Snyk CLI
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      # Step 5: Run Snyk test
      - name: Run Snyk test
        run: snyk test

      # Step 6: (Optional) Monitor the project in Snyk
      - name: Monitor project in Snyk
        run: snyk monitor